### PR TITLE
Merge opened PRs into gh-pages branch

### PR DESCRIPTION
**Pull request by benoittgt**
Doing the assign tasks from https://github.com/lelylan/betterspecs/issues/168#issuecomment-187756063
Closes #138, closes #164

Was not able to found any book links for #137. So didn't fixe this one. Was simpler to redo all the changes. Less git more vim. 💕

_Edited by @onebree to unlink PR 135._

### CODE REVIEW

**Comment by onebree** [comment]
@benoittgt I see what you mean -- If it is not too much trouble, you can create another PR which adds a "Resources" section before "Contributing".

Also, I may not have been clear, but the point of this PR was to grab the commits that others have made and implement them in `gh-pages`. I want the original PR authors to have their commits published, as they helped us out. I can better explain this on Slack if you need help.

Sop as of right now, I am adding `[WIP]` to this PR title.

**Comment by benoittgt** [comment]
No problem I can do the merge.

**Comment by onebree** [comment]
@benoittgt you did not need to close this PR -- you could have just done `git reset --hard <parent-of-c35ee29>` and `git push origin <branch-name> --force`

**Comment by benoittgt** [comment]
Did a try at lunch time. Damn too long. Sorry @onebree. I know it's important to keep history of who commit but I can't fixe for each PR so many merge conflicts on Gemfile.lock, Procfile... to add an `s` to rspec...

**Comment by onebree** [comment]
@benoittgt let me take a stab at it -- I appreciate your help in this.

**Comment by onebree** [comment]
@benoittgt I took a stab at it myself. Following my initial instructions brought all the old files back, which is not what we want. From there, I tried `cherry-pick`, but this did the same thing. I am going to merge your PR, and just include the helpful usernames in the commit message.

As a note, I looked up #135, and it deals with the currently-missing "Resources" section. I will edit your comment to remove that PR, so it does not close.

Thank you for the help!

**Comment by benoittgt** [comment]
Thanks @onebree :clap:

**Pull request merged**
