### PR TITLE
Fix "Easy to read matchers" index entry to match section title

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by onebree** [comment]
@DavidS does this change need to be added to the translation pages?

**Comment by DavidS** [comment]
Maybe. How would I know? I speak none of those languages.

**Comment by onebree** [comment]
@DavidS -- if you read the conversation in #171, you will see that your commits helped us out.. We were just unable to apply them properly. I gave you attribution (username, commit hash) in the merge commit message.

**Comment by DavidS** [comment]
@onebree that's entirely fine! Thanks for this great resource.

**Pull request closed without merging**
